// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAIOZGmKILFhZgXp3p7kgYS-AAVPSKUh8',
    appId: '1:450026241130:web:af415d1f8debbd670e9e13',
    messagingSenderId: '450026241130',
    projectId: 'amudhu-6505f',
    authDomain: 'amudhu-6505f.firebaseapp.com',
    storageBucket: 'amudhu-6505f.firebasestorage.app',
    measurementId: 'G-FQLM4G5P20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Tg7JK9wbtrgKB-dZTtqD9hHY1YHKCIc',
    appId: '1:450026241130:android:5f361299b63076fa0e9e13',
    messagingSenderId: '450026241130',
    projectId: 'amudhu-6505f',
    storageBucket: 'amudhu-6505f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXovj1Ce7w3_jV3jFxcnJ0wsa71peDfrQ',
    appId: '1:450026241130:ios:24d303bfeef36b010e9e13',
    messagingSenderId: '450026241130',
    projectId: 'amudhu-6505f',
    storageBucket: 'amudhu-6505f.firebasestorage.app',
    iosClientId: '450026241130-t34mpofrt7nbgt1cvgd6tej68ebo89h1.apps.googleusercontent.com',
    iosBundleId: 'com.example.amudu',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXovj1Ce7w3_jV3jFxcnJ0wsa71peDfrQ',
    appId: '1:450026241130:ios:24d303bfeef36b010e9e13',
    messagingSenderId: '450026241130',
    projectId: 'amudhu-6505f',
    storageBucket: 'amudhu-6505f.firebasestorage.app',
    iosClientId: '450026241130-t34mpofrt7nbgt1cvgd6tej68ebo89h1.apps.googleusercontent.com',
    iosBundleId: 'com.example.amudu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAIOZGmKILFhZgXp3p7kgYS-AAVPSKUh8',
    appId: '1:450026241130:web:d58d967876886aff0e9e13',
    messagingSenderId: '450026241130',
    projectId: 'amudhu-6505f',
    authDomain: 'amudhu-6505f.firebaseapp.com',
    storageBucket: 'amudhu-6505f.firebasestorage.app',
    measurementId: 'G-49DQKGTTE2',
  );
}
